services:

  selenium-hub:
    image: selenium/hub:4.36.0
    container_name: selenium-hub
    platform: linux/amd64
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.36.0
#    container_name: selenium-chrome if you want to scale it you can't give custom name as all container will use same name
    platform: linux/amd64
    shm_size: "2gb"

    depends_on:
      - selenium-hub

    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: "4442"
      SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"

  java-tests:
    build:
      context: .
    container_name: java-cucumber-runner

    depends_on:
      - selenium-hub
      - chrome

    environment:
     runMode: docker

    command: mvn test -DrunMode=docker